export const GET = async (request) => {
    const data = [
        {
            imageUrl: "/assets/images/post-image.png",
            name: "Lorem Ipsum",
            desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.Lorem Ipsum is",
            sector: 1,
            likes: "2k",
            views: "2k",
            comments: "2k",
            timestamp: "2 mins ago",
        },
        {
            name: "Lorem Ipsum",
            desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.Lorem Ipsum is",
            sector: 1,
            likes: "2k",
            views: "2k",
            comments: "2k",
            timestamp: "2 mins ago",
        },
        {
            imageUrl: "/assets/images/post-image.png",
            name: "Lorem Ipsum",
            desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.Lorem Ipsum is",
            sector: 1,
            likes: "2k",
            views: "2k",
            comments: "2k",
            timestamp: "2 mins ago",
        },
        {
            name: "Lorem Ipsum",
            desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.Lorem Ipsum is",
            sector: 1,
            likes: "2k",
            views: "2k",
            comments: "2k",
            timestamp: "2 mins ago",
        },
        {
            imageUrl: "/assets/images/post-image.png",
            name: "Lorem Ipsum",
            desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.Lorem Ipsum is",
            sector: 1,
            likes: "2k",
            views: "2k",
            comments: "2k",
            timestamp: "2 mins ago",
        },
        {
            name: "Lorem Ipsum",
            desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.Lorem Ipsum is",
            sector: 1,
            likes: "2k",
            views: "2k",
            comments: "2k",
            timestamp: "2 mins ago",
        },
        {
            imageUrl: "/assets/images/post-image.png",
            name: "Lorem Ipsum",
            desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.Lorem Ipsum is",
            sector: 1,
            likes: "2k",
            views: "2k",
            comments: "2k",
            timestamp: "2 mins ago",
        },
        {
            name: "Lorem Ipsum",
            desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.Lorem Ipsum is",
            sector: 1,
            likes: "2k",
            views: "2k",
            comments: "2k",
            timestamp: "2 mins ago",
        },
        {
            imageUrl: "/assets/images/post-image.png",
            name: "Lorem Ipsum",
            desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.Lorem Ipsum is",
            sector: 1,
            likes: "2k",
            views: "2k",
            comments: "2k",
            timestamp: "2 mins ago",
        },
        {
            name: "Lorem Ipsum",
            desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.Lorem Ipsum is",
            sector: 1,
            likes: "2k",
            views: "2k",
            comments: "2k",
            timestamp: "2 mins ago",
        },
    ];

    return new Response(JSON.stringify(data), { status: 200 });
};
